### ISSUE TITLE
[bug] failed overriding protocol method -[WKUIDelegate webView:requestMediaCapturePermissionForOrigin:initiatedByFrame:type:decisionHandler:]: method not found

### ISSUE THREAD

**Issue by yuandapeng** [tauri-apps/tauri#11496]
### Describe the bug

npm run tauri dev

> tauri-app@0.1.0 tauri
> tauri dev

    Running BeforeDevCommand (`npm run dev`)

> tauri-app@0.1.0 dev
> vite

    Warn Waiting for your frontend dev server to start on http://localhost:1420/...
Re-optimizing dependencies because lockfile has changed

  VITE v5.4.10  ready in 3410 ms

  ➜  Local:   http://localhost:1420/
    Info Watching /Users/peipeng.yuan.o/workspace/tauri-app/src-tauri for changes...
   Compiling objc-sys v0.3.5
   Compiling objc2 v0.5.2
   Compiling block2 v0.5.1
   Compiling objc2-foundation v0.2.2
   Compiling objc2-app-kit v0.2.2
   Compiling objc2-web-kit v0.2.2
   Compiling window-vibrancy v0.5.2
   Compiling muda v0.15.1
   Compiling wry v0.46.3
   Compiling tauri-runtime-wry v2.1.2
   Compiling tauri v2.0.6
   Compiling tauri-plugin-shell v2.0.2
   Compiling tauri-app v0.1.0 (/Users/peipeng.yuan.o/workspace/tauri-app/src-tauri)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 54.44s
thread 'main' panicked at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/__macro_helpers/declare_class.rs:339:21:
failed overriding protocol method -[WKUIDelegate webView:requestMediaCapturePermissionForOrigin:initiatedByFrame:type:decisionHandler:]: method not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x1029e90b6 - std::backtrace_rs::backtrace::libunwind::trace::hae28e9d8ee6f0f1b
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:        0x1029e90b6 - std::backtrace_rs::backtrace::trace_unsynchronized::h97ac52ce5b001ab9
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1029e90b6 - std::sys::backtrace::_print_fmt::h121f81f3e644bc1c
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:66:9
   3:        0x1029e90b6 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hcaf66bc4c0c453df
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:39:26
   4:        0x102a0aedb - core::fmt::rt::Argument::fmt::hfeba5accca924a15
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/rt.rs:177:76
   5:        0x102a0aedb - core::fmt::write::hc9c5f1836b413410
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/mod.rs:1178:21
   6:        0x1029e5b92 - std::io::Write::write_fmt::h49df280499063c09
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/mod.rs:1823:15
   7:        0x1029ea3c8 - std::sys::backtrace::BacktraceLock::print::he68bab4b1e212a89
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:42:9
   8:        0x1029ea3c8 - std::panicking::default_hook::{{closure}}::h52c0b2f44f6107c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:266:22
   9:        0x1029ea00e - std::panicking::default_hook::h5a6cf31501c161b2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:293:9
  10:        0x1029eb0e3 - std::panicking::rust_panic_with_hook::hda4640ee332466e9
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:797:13
  11:        0x1029ea982 - std::panicking::begin_panic_handler::{{closure}}::haa3060694b34ea3d
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:664:13
  12:        0x1029e9599 - std::sys::backtrace::__rust_end_short_backtrace::h8eb44913cfe71457
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
  13:        0x1029ea5fc - rust_begin_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
  14:        0x102a3d25c - core::panicking::panic_nounwind_fmt::runtime::h192b7a91100d1ba6
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:112:18
  15:        0x102a3d25c - core::panicking::panic_nounwind_fmt::hfed0a2f12e4318b1
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:122:5
  16:        0x102a3d30a - core::panicking::panic_nounwind::h659854746b9fc37d
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:221:5
  17:        0x102a3d525 - core::panicking::panic_cannot_unwind::hd982c2e1ccbf0ef4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:310:5
  18:        0x10242e9ca - tao::platform_impl::platform::app_delegate::did_finish_launching::h1e4a275343ef8f00
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.30.3/src/platform_impl/macos/app_delegate.rs:103:1
  19:     0x7fff20495463 - <unknown>
  20:     0x7fff20530ed9 - <unknown>
  21:     0x7fff20530e54 - <unknown>
  22:     0x7fff204666ce - <unknown>
  23:     0x7fff211d9c18 - <unknown>
  24:     0x7fff22cb0d80 - <unknown>
  25:     0x7fff22cb0ad2 - <unknown>
  26:     0x7fff22cadc71 - <unknown>
  27:     0x7fff22cad8c7 - <unknown>
  28:     0x7fff21205366 - <unknown>
  29:     0x7fff212051d6 - <unknown>
  30:     0x7fff26282853 - <unknown>
  31:     0x7fff26281f6e - <unknown>
  32:     0x7fff2627acd3 - <unknown>
  33:     0x7fff286fa012 - <unknown>
  34:     0x7fff22ca7f70 - <unknown>
  35:     0x7fff22ca62a5 - <unknown>
  36:     0x7fff22c985c9 - <unknown>
  37:        0x10246aff1 - <() as objc::message::MessageArguments>::invoke::h99676cb39a047150
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:128:17
  38:        0x102469bbd - objc::message::platform::send_unverified::h00753cbb8fff113e
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:27:9
  39:        0x1020f0295 - objc::message::send_message::h699c43327ef8383e
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:178:5
  40:        0x1020f0295 - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::h9fc62e1d792f5527
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.30.3/src/platform_impl/macos/event_loop.rs:225:16
  41:        0x1020f1161 - tao::platform_impl::platform::event_loop::EventLoop<T>::run::hd25c501f4a144ef6
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.30.3/src/platform_impl/macos/event_loop.rs:192:21
  42:        0x102161a88 - tao::event_loop::EventLoop<T>::run::hb2375ddcff1fbe5c
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.30.3/src/event_loop.rs:215:5
  43:        0x101bb2c1b - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::hc6d4738815a0d29e
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-2.1.2/src/lib.rs:2726:5
  44:        0x101bb931a - tauri::app::App<R>::run::h7d298a0e7089e2ef
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.6/src/app.rs:1129:5
  45:        0x101bb9df5 - tauri::app::Builder<R>::run::h3f745a7e6b0402fa
                               at /Users/peipeng.yuan.o/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.6/src/app.rs:2052:5
  46:        0x10218d3f9 - tauri_app_lib::run::h53568fe4fe82bff6
                               at /Users/peipeng.yuan.o/workspace/tauri-app/src-tauri/src/lib.rs:9:5
  47:        0x10192cc89 - tauri_app::main::hf333b231e8f5fa62
                               at /Users/peipeng.yuan.o/workspace/tauri-app/src-tauri/src/main.rs:5:5
  48:        0x10192cd6e - core::ops::function::FnOnce::call_once::h36fa293f72247906
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  49:        0x10192cc71 - std::sys::backtrace::__rust_begin_short_backtrace::h7639879eaae778c1
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:154:18
  50:        0x10192cd24 - std::rt::lang_start::{{closure}}::h4cda7cd945a37f68
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:164:18
  51:        0x1029e141f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h57d1f2389e2919e9
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:284:13
  52:        0x1029e141f - std::panicking::try::do_call::h47b836309ad2925a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  53:        0x1029e141f - std::panicking::try::hcc79b4069713f450
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  54:        0x1029e141f - std::panic::catch_unwind::h34090fdb34bc5e00
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  55:        0x1029e141f - std::rt::lang_start_internal::{{closure}}::hb9c7217a630c43c9
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:48
  56:        0x1029e141f - std::panicking::try::do_call::h43e7c27d402b50a4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  57:        0x1029e141f - std::panicking::try::h4d79f623873fbc60
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  58:        0x1029e141f - std::panic::catch_unwind::hb32f8cfbf49d3dee
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  59:        0x1029e141f - std::rt::lang_start_internal::hb1473645dbe40065
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:20
  60:        0x10192ccf7 - std::rt::lang_start::h74b59529f543ed2f
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:163:17
  61:        0x10192cca8 - _main
thread caused non-unwinding panic. aborting.

### Full `tauri info` output

```text
tauri info


[✔] Environment
    - OS: Mac OS 11.7.10 x86_64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.16.0
    - pnpm: 9.10.0
    - yarn: 1.22.19
    - npm: 10.8.1

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by yuandapeng** [comment]
When I upgraded to the latest version of Mac OS 15.0.1 x86_64 (X64), this problem was solved.
tauri info
[✔] Environment
    - OS: Mac OS 15.0.1 x86_64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.16.0
    - pnpm: 9.10.0
    - yarn: 1.22.19
    - npm: 10.8.1

**Comment by lucasfernog** [comment]
the crash is caused due to a debug check in the objc2 crate;
until they release a fix, you should add the following to your Cargo.toml file:
```toml
[profile.dev.package.objc2]
debug-assertions = false
```
see https://github.com/madsmtm/objc2/issues/645#issuecomment-2319980814 for more information

**Comment by FabianLars** [comment]
If you use tauri 2.3+ running `cargo update -p wry` should pull in the fix

**Comment by pronebird** [comment]
@FabianLars I am still seeing this crash though despite updating to tauri 2.7 and using wry 0.52.1

**Comment by FabianLars** [comment]
can you share the full error you get?

**Comment by pronebird** [comment]
@FabianLars 

```
% npm run tauri dev

> tauri
> tauri dev

        Info `tauri-build` dependency has workspace inheritance enabled. The features array won't be automatically rewritten. Expected features: []
        Info `tauri` dependency has workspace inheritance enabled. The features array won't be automatically rewritten. Expected features: []
     Running BeforeDevCommand (`npm run dev`)

> dev
> vite


  VITE v5.4.19  ready in 257 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
     Running DevCommand (`cargo  run --no-default-features --color always --`)
        Info Watching /Users/pronebird/dev/my-cool-app/my-cool-app/src-tauri for changes...
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.59s
     Running `/Users/pronebird/dev/my-cool-app/target/debug/my-cool-app`

thread 'main' panicked at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.1/src/__macro_helpers/define_class.rs:328:21:
failed overriding protocol method -[WKUIDelegate webView:requestMediaCapturePermissionForOrigin:initiatedByFrame:type:decisionHandler:]: method not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at library/core/src/panicking.rs:226:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10cd148ee - std::backtrace_rs::backtrace::libunwind::trace::h0d77f66cff0ee92a
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:        0x10cd148ee - std::backtrace_rs::backtrace::trace_unsynchronized::h8ad8693b125c09a6
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:        0x10cd148ee - std::sys::backtrace::_print_fmt::haea0c12219927921
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:66:9
   3:        0x10cd148ee - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h9d61884e08d3316c
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:39:26
   4:        0x10cd37393 - core::fmt::rt::Argument::fmt::h99fa920ea7062e63
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:181:76
   5:        0x10cd37393 - core::fmt::write::ha7e42c8550512cfb
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:1446:25
   6:        0x10cd10ee2 - std::io::default_write_fmt::h78d0fa29d875c928
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:639:11
   7:        0x10cd10ee2 - std::io::Write::write_fmt::h8dd7e3932392f4be
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:1914:13
   8:        0x10cd14732 - std::sys::backtrace::BacktraceLock::print::h972ba80fe25d05e0
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:42:9
   9:        0x10cd15fd0 - std::panicking::default_hook::{{closure}}::h05218cad2d40e027
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:300:22
  10:        0x10cd15ddb - std::panicking::default_hook::hd9c10aab77439366
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:327:9
  11:        0x10cd16b62 - std::panicking::rust_panic_with_hook::hb1fd245af5672dcd
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:833:13
  12:        0x10cd16755 - std::panicking::begin_panic_handler::{{closure}}::hf868e10834208483
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:699:13
  13:        0x10cd14db9 - std::sys::backtrace::__rust_end_short_backtrace::haac0e906ed75717a
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
  14:        0x10cd163c4 - __rustc[4794b31dd7191200]::rust_begin_unwind
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
  15:        0x10cd74984 - core::panicking::panic_nounwind_fmt::runtime::ha95d19de7f158e7a
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:117:22
  16:        0x10cd74984 - core::panicking::panic_nounwind_fmt::h82bea23087e0bb7b
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/intrinsics/mod.rs:3196:9
  17:        0x10cd74a2a - core::panicking::panic_nounwind::h1486263b15958903
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:226:5
  18:        0x10cd74be0 - core::panicking::panic_cannot_unwind::hee35ed8b73b78d65
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:331:5
  19:        0x10c5d9409 - tao::platform_impl::platform::app_delegate::did_finish_launching::ha452cd8090934bcf
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.34.0/src/platform_impl/macos/app_delegate.rs:114:1
  20:     0x7fff205b5463 - <unknown>
  21:     0x7fff20650ed9 - <unknown>
  22:     0x7fff20650e54 - <unknown>
  23:     0x7fff205866ce - <unknown>
  24:     0x7fff212f9c18 - <unknown>
  25:     0x7fff22dd0d80 - <unknown>
  26:     0x7fff22dd0ad2 - <unknown>
  27:     0x7fff22dcdc71 - <unknown>
  28:     0x7fff22dcd8c7 - <unknown>
  29:     0x7fff21325366 - <unknown>
  30:     0x7fff213251d6 - <unknown>
  31:     0x7fff263a2853 - <unknown>
  32:     0x7fff263a1f6e - <unknown>
  33:     0x7fff2639acd3 - <unknown>
  34:     0x7fff2881a012 - <unknown>
  35:     0x7fff22dc7f70 - <unknown>
  36:     0x7fff22dc62a5 - <unknown>
  37:     0x7fff22db85c9 - <unknown>
  38:        0x10c8b4e70 - <() as objc2::encode::EncodeArguments>::__invoke::h7ada87b56f3d381f
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.1/src/encode.rs:433:26
  39:        0x10c8b1970 - objc2::runtime::message_receiver::msg_send_primitive::send::ha5d3bdcdc0d070d5
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.1/src/runtime/message_receiver.rs:172:18
  40:        0x10c8a96a0 - objc2::runtime::message_receiver::MessageReceiver::send_message::hc2814ffd2d0289d4
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.1/src/runtime/message_receiver.rs:432:38
  41:        0x10ba935f7 - <MethodFamily as objc2::__macro_helpers::msg_send_retained::MsgSend<Receiver,Return>>::send_message::h329af6dc628a9426
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.1/src/__macro_helpers/msg_send_retained.rs:35:28
  42:        0x10bac66d3 - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::hcbe6f5b9a9355d7f
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.34.0/src/platform_impl/macos/event_loop.rs:234:16
  43:        0x10bac6c71 - tao::platform_impl::platform::event_loop::EventLoop<T>::run::hf8b7e490aff6027b
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.34.0/src/platform_impl/macos/event_loop.rs:201:21
  44:        0x10bdeda0d - tao::event_loop::EventLoop<T>::run::hacdb753c1ef5123a
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.34.0/src/event_loop.rs:215:5
  45:        0x10bb8517c - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::hce00864e9cc31b4b
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-runtime-wry-2.7.2/src/lib.rs:3019:5
  46:        0x10bb54517 - tauri::app::App<R>::run::h8c86c24e421611ea
                               at /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-2.7.0/src/app.rs:1234:5
  47:        0x10bd8fc97 - my_cool_app::main::h18b2e12ae934b878
                               at /Users/pronebird/dev/my-cool-app/my-cool-app/src-tauri/src/main.rs:69:5
  48:        0x10bd30e5e - core::ops::function::FnOnce::call_once::h93efadca8782bc11
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
  49:        0x10ba8e1d1 - std::sys::backtrace::__rust_begin_short_backtrace::h3f0e2287169e5cd4
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:152:18
  50:        0x10bd12344 - std::rt::lang_start::{{closure}}::h446233c297006da7
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/rt.rs:199:18
  51:        0x10cd0abbe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha55a0ab309b334cf
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:284:13
  52:        0x10cd0abbe - std::panicking::try::do_call::h96a651454383b77e
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
  53:        0x10cd0abbe - std::panicking::try::hbf3bdd887cce5625
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
  54:        0x10cd0abbe - std::panic::catch_unwind::h03d328d69a45f835
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
  55:        0x10cd0abbe - std::rt::lang_start_internal::{{closure}}::h0a5b56aa78daf5eb
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/rt.rs:168:24
  56:        0x10cd0abbe - std::panicking::try::do_call::h0e893e4e0866d6a8
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
  57:        0x10cd0abbe - std::panicking::try::h54599c1dea73fdfe
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
  58:        0x10cd0abbe - std::panic::catch_unwind::h24f5c5189a2fae11
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
  59:        0x10cd0abbe - std::rt::lang_start_internal::ha8dd1a9b824efcda
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/rt.rs:164:5
  60:        0x10bd12327 - std::rt::lang_start::ha23408df6d3b68e6
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/rt.rs:198:5
  61:        0x10bd90fd8 - _main
thread caused non-unwinding panic. aborting.
```

I have tried activating `"disable-encoding-assertions"` feature for `objc2` but no luck. 
macOS 11.7.10

**Comment by FabianLars** [comment]
> I have tried activating "disable-encoding-assertions" feature for objc2 but no luck.

We already enable that in wry. I don't have any ideas right now so i'll just re-open this and try to reproduce it in a VM.

**Comment by pronebird** [comment]
> > I have tried activating "disable-encoding-assertions" feature for objc2 but no luck.
> 
> We already enable that in wry. I don't have any ideas right now so i'll just re-open this and try to reproduce it in a VM.

Thanks. Let me know if you want me to test some assumptions. I have a physical MacBook with big sur

**Comment by pzx521521** [comment]
When running/building a Tauri app (using wry v0.53+) on macOS 11.x or macOS 12.0–12.2, the application crashes at startup with: 

`thread 'main' (972984) panicked at library/core/src/panicking.rs:225:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10de7aee6 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h85fe5e9dc1957b72
   1:        0x10dec66df - core::fmt::write::h1fa1572c63806a93
   2:        0x10de91a5e - std::io::default_write_fmt::h86c082182d86b355
   3:        0x10deab5c0 - std::io::Write::write_fmt::h59fbbf6e6aff08f2
   4:        0x10de79a73 - std::sys::backtrace::BacktraceLock::print::h25a77f22d9ebb5cc
   5:        0x10de9e19b - std::panicking::default_hook::{{closure}}::h2dd454c10e5f7f7e
   6:        0x10de9e046 - std::panicking::default_hook::h00185b6eb95a1151
   7:        0x10de9e43e - std::panicking::panic_with_hook::he933b7bc0318d161
   8:        0x10de79dd5 - std::panicking::panic_handler::{{closure}}::h9db69391c7b95a51
   9:        0x10de79b89 - std::sys::backtrace::__rust_end_short_backtrace::ha72f6bbef60f26f2
  10:        0x10de9c464 - __rustc[bd3b3f48d2381c32]::rust_begin_unwind
  11:        0x10def27a4 - core::panicking::panic_nounwind_fmt::h373761f5d118b214
  12:        0x10def26ca - core::panicking::panic_nounwind::ha27d82c06e325c40
  13:        0x10def28e5 - core::panicking::panic_cannot_unwind::h7a20241b34d5ed78
  14:        0x10db2a0b9 - tao::platform_impl::platform::app_delegate::did_finish_launching::h13099b4bbbfaa04f
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.34.5/src/platform_impl/macos/app_delegate.rs:126:1
  15:     0x7fff20921463 - <unknown>
  16:     0x7fff209bced9 - <unknown>
  17:     0x7fff209bce54 - <unknown>
  18:     0x7fff208f26ce - <unknown>
  19:     0x7fff21665c18 - <unknown>
  20:     0x7fff2313cd80 - <unknown>
  21:     0x7fff2313cad2 - <unknown>
  22:     0x7fff23139c71 - <unknown>
  23:     0x7fff231398c7 - <unknown>
  24:     0x7fff21691366 - <unknown>
  25:     0x7fff216911d6 - <unknown>
  26:     0x7fff2670e853 - <unknown>
  27:     0x7fff2670df6e - <unknown>
  28:     0x7fff26706cd3 - <unknown>
  29:     0x7fff28b86012 - <unknown>
  30:     0x7fff23133f70 - <unknown>
  31:     0x7fff231322a5 - <unknown>
  32:     0x7fff231245c9 - <unknown>
  33:        0x10dc61e50 - <() as objc2::encode::EncodeArguments>::__invoke::h6a642a3bfe92b92b
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.3/src/encode.rs:433:26
  34:        0x10dc66170 - objc2::runtime::message_receiver::msg_send_primitive::send::h72ab89541422eb2a
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.3/src/runtime/message_receiver.rs:172:18
  35:        0x10dc5aaa0 - objc2::runtime::message_receiver::MessageReceiver::send_message::h25884ccfca6baa9c
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.3/src/runtime/message_receiver.rs:432:38
  36:        0x10d609807 - <MethodFamily as objc2::__macro_helpers::msg_send_retained::MsgSend<Receiver,Return>>::send_message::hd0a8770b19771224
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-0.6.3/src/__macro_helpers/msg_send_retained.rs:35:28
  37:        0x10d573e03 - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::h7110c4a5e3c9a5fa
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.34.5/src/platform_impl/macos/event_loop.rs:234:16
  38:        0x10d574371 - tao::platform_impl::platform::event_loop::EventLoop<T>::run::h594b3d887fd67745
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.34.5/src/platform_impl/macos/event_loop.rs:201:26
  39:        0x10d7c5f1d - tao::event_loop::EventLoop<T>::run::h6cc2205631f44c9a
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.34.5/src/event_loop.rs:214:21
  40:        0x10d66340c - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::h6f1e266c016290b9
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-runtime-wry-2.9.3/src/lib.rs:3087:21
  41:        0x10d563437 - tauri::app::App<R>::run::h8eda0cc967e4dfd9
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-2.9.5/src/app.rs:1249:8
  42:        0x10d563a8f - tauri::app::Builder<R>::run::ha52210426e1a8311
                               at /Users/parapeng/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-2.9.5/src/app.rs:2301:26
  43:        0x10d7aee6a - tauri_app_lib::run::he241da52614d1a30
                               at /Users/parapeng/Desktop/rust/tauri-app/src-tauri/src/lib.rs:12:10
  44:        0x10d529e99 - tauri_app::main::hc7b4a3012e8b102e
                               at /Users/parapeng/Desktop/rust/tauri-app/src-tauri/src/main.rs:5:5
  45:        0x10d529fae - core::ops::function::FnOnce::call_once::h7107732d30cde7c7
                               at /opt/local/libexec/rust/src/rustc-1.91.1-src/library/core/src/ops/function.rs:250:5
  46:        0x10d529fd1 - std::sys::backtrace::__rust_begin_short_backtrace::h811ed5780a2d81af
                               at /opt/local/libexec/rust/src/rustc-1.91.1-src/library/std/src/sys/backtrace.rs:158:18
  47:        0x10d529f24 - std::rt::lang_start::{{closure}}::h36b8a4cd57f6e1c6
                               at /opt/local/libexec/rust/src/rustc-1.91.1-src/library/std/src/rt.rs:206:18
  48:        0x10deab695 - std::rt::lang_start_internal::h57d4c34cd10d3203
  49:        0x10d529f07 - std::rt::lang_start::h7781cb09c5a2acc2
                               at /opt/local/libexec/rust/src/rustc-1.91.1-src/library/std/src/rt.rs:205:5
  50:        0x10d529eb8 - _main
thread caused non-unwinding panic. aborting.`


**To Reproduce**

Create a Tauri app with wry ≥ v0.53 (e.g., Tauri v2.9+)
Build it on any macOS
Run/Build the app on macOS 11.7.10 (or any version <12.3)
Observe immediate panic during WebView initialization


**Expected behavior**
The app should start normally. Media capture permission is not required for most apps, and even if needed, the delegate method should only be registered if supported by the OS.

**Platform and Versions**

+ macOS: 11.7.10 (Big Sur)
+ wry: v0.53.5
+ objc2: v0.6.3
+ Tauri: v2.9.2

**Additional context**
The method [webView:requestMediaCapturePermissionForOrigin:initiatedByFrame:type:decisionHandler:](https://developer.apple.com/documentation/webkit/wkuidelegate/3967365-webview) was introduced in macOS 12.3.
However, wry unconditionally implements it in WryWebViewUIDelegate](https://github.com/tauri-apps/wry/blob/dev/src/wkwebview/class/wry_web_view_ui_delegate.rs#L129):

**Suggested Fix**
Do not register this delegate method on macOS <12.3. Since Rust cannot detect macOS runtime version easily, safe options include:

Remove the method entirely (recommended for now, as most apps don’t use media capture)
Add a compile-time feature flag (e.g., media-capture-permission) to enable it only when needed
Implement runtime method existence check using class_respondsToSelector (requires objc2 support for conditional protocol conformance)
**Note: Tauri documents macOS 10.15+ as minimum, but this bug breaks compatibility with macOS 11.**
