### ISSUE TITLE
[bug] Can't compile tauri with 2.0.6 & latest of tauri running exception !!!

### ISSUE THREAD

**Issue by barbyJam** [tauri-apps/tauri#11887]
### Describe the bug

1. Can't compile tauri with 2.0.6:
- In those months, I can use tauri 2.0.6 all of functions correctly. However, today I recomplie my program, it can't pass the complier, error info is:

       error[E0061]: this method takes 2 arguments but 3 arguments were supplied
         --> C:\Users\Test\.cargo\registry\src\mirrors\tauri-2.0.6\src\window\mod.rs:386:22
          |
      386 |                     .attach_webview(window.clone(), webview, None);
          |                      ^^^^^^^^^^^^^^                          ---- unexpected argument #3 of type `std::option::Option<_>`
          |
      note: method defined here
         --> C:\Users\Test\.cargo\registry\src\mirrors\tauri-2.0.6\src\manager\webview.rs:571:17
          |
      571 |   pub(crate) fn attach_webview(
          |                 ^^^^^^^^^^^^^^
      572 |     &self,
      573 |     window: Window<R>,
          |     -----------------
      574 |     webview: DetachedWebview<EventLoopMessage, R>,
          |     ---------------------------------------------
      help: remove the extra argument
          |
      386 -                     .attach_webview(window.clone(), webview, None);
      386 +                     .attach_webview(window.clone(), webview);
          |
      
      For more information about this error, try `rustc --explain E0061`.
      error: could not compile `tauri` (lib) due to 1 previous error

2. Latest of tauri running exception:
- Because of above those problems, I try to use the latest version to build my program, it can be passed the compile, but UI can't be  display correctly:
#### Location wrong:
- I set up : `decorations=false`, `center: true`
In fact, when the program staring, it can't be located in the monitor center(tauri 2.0.0 do have not this problem)

#### Layout change:
- May above the problem, the page layout have something change. Such as, font size, widget height, etc.

### Reproduction

All of developer can download my program [tauri-test.zip](https://github.com/user-attachments/files/18040347/tauri-test.zip).

### Expected behavior

1. When you compile my program, you can find my problem that I say.
2. You could make a latest program by `npm create tauri-app@latest`, and set `tauri.conf.json` 's configuration: `center: true`, you can see my mention's location/display problem.

### Full `tauri info` output

```text
Plase see the `Describe the bug` area.
```

### Additional context

I do love tauri, this problem is too difficult for me to sovle it, please help me, thanks.

**Comment by FabianLars** [comment]
> In those months, I can use tauri 2.0.6 all of functions correctly. However, today I recomplie my program, it can't pass the complier, error info is:

i think this can only happen if _some_ packages are updated but not all, or some issue in the local copy of the registry. Try deleting the Cargo.lock file and check again maybe.

> I set up : decorations=false, center: true
In fact, when the program staring, it can't be located in the monitor center(tauri 2.0.0 do have not this problem)

This should be fixed on the next release

> May above the problem, the page layout have something change. Such as, font size, widget height, etc.

I think this is the first time i hear about this 🤔 (I didn't check out your test files yet though)

> All of developer can download my program

Please never upload zip files, we and others can't just trust them. Upload the files as a github repository instead please :)

**Comment by barbyJam** [comment]
Latest the source code is uploaded to [https://github.com/barbyJam/tauri-issue-11887](https://github.com/barbyJam/tauri-issue-11887)

### 1. About of the 2.0.6 can' be compile's problem, I have tried to delete cargo.lock and limit the Cargo.toml package to below info:

> [build-dependencies]
> tauri-build = { version = "=2.0.6", features = [] }
> 
> [dependencies]
> tauri = { version = "=2.0.6", features = [] }

it still dont't work.

### 2. Thanks you will resolve this problem that app don't centerize.
 
### 3. I re-description about the display of the widget layout problem.
#### Running the program with the v2.0.6, the window size is 1000x750:
![image](https://github.com/user-attachments/assets/2344de3c-e491-4cb2-8d20-2fde45acdcca)

#### In the same code with the v2.1.1, the window size is 1016x794.
![image](https://github.com/user-attachments/assets/406b917d-a817-4d74-8e98-ed9086ace40f)

I guest that because of the change of the window size, the layout have been broken. Please tell me how to resolve it?

**Comment by FabianLars** [comment]
> 1 About of the 2.0.6 can' be compile's problem, I have tried to delete cargo.lock and limit the Cargo.toml package to below info:

You have to lock all the inner crates too. That's a bit annoying since they don't have the same patch/minor versions as the top level tauri depency, so it requires a bit trial and error

> 3 I re-description about the display of the widget layout problem.

Ahh i see, i think this is more or less related to the centering issue and should also be fixed on the next release
