### ISSUE TITLE
[bug] Window.setSize() isn't working when "decoration" set to false

### ISSUE THREAD

**Issue by brigazvi** [tauri-apps/tauri#11975]
### Describe the bug

I can't resize the window when the window "decorations" are set to false.

### Reproduction

- create a new Tauri project.
- set the window decoration to false (programmatically with permissions or via tuari.conf.json)
- add permission to resize the window in src-tauri/capabilities/default.json with `core:window:allow-set-size`.
- in the code, get the current window and try to resize it with the setSize function, for example:
```
const currentWindow = getCurrentWindow();
await currentWindow.setSize(new PhysicalSize(300, 1000));
```
### Expected behavior

the windows should resize. or at least I should get an error in the console.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 131.0.2903.99
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.16.0
    - pnpm: 9.12.3
    - npm: 10.8.1
    - deno: deno 2.1.2

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.2.0
    - @tauri-apps/plugin-shell : 2.2.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

I've tried to go around it by setting "decorations" to "true" before changing the size and then changing it back to "false" after the resize. but because setSize() sets the inner size, changing "decoration" to false adds a little bit of height, and the result isn't quite right.

**Comment by FabianLars** [comment]
fixed on next release

**Comment by brigazvi** [comment]
@FabianLars thank u.

**Comment by Ali-Khazaee** [comment]
@FabianLars next release time ?

**Comment by keneth7** [comment]
Hello, this issue still exists. I am using the latest version, 2.5.1.

> fixed on next release

**Comment by FabianLars** [comment]
@keneth7 please share the output of the tauri info command.
