### ISSUE TITLE
EdgeHTML: Cannot execute webview.eval immediately after startup (replaces #190)

### ISSUE THREAD

**Issue by BenoitRanque** [tauri-apps/tauri#212]
OS: Windows

This is a replacement for #190, as after more research the title has become misleading and the issue is becoming clearer.

EdgeHTML is currently bugged: [`webview.eval()`](https://docs.rs/web-view/0.5.4/web_view/struct.WebView.html#method.eval) may fail silently when executed in a closure dispatched during startup. Related [issue](https://github.com/zserge/webview/issues/301) on webview.

<details><summary>Show Case</summary>

```rs
use web_view::*

fn main() {
    let webview = web_view::builder()
        .title("Timer example")
        .content(Content::Html(HTML))
        .size(800, 600)
        .resizable(true)
        .debug(true)
        .user_data(0)
        .invoke_handler(|_webview, _arg| Ok(()))
        .build()
        .unwrap();

    // to showcase the bug, we try to add multiple items to the page.
    // only some will show. If your computer is too performant, maybe none
    // if that happens make the for loop bigger.

    let handle = webview.handle();
    for i in 0..1000 {
        handle.dispatch(move |webview| {
            webview.eval(&format!("document.body.appendChild(document.createElement('p')).appendChild(document.createTextNode('Item {}'))", i))
        }).unwrap();
    }
    webview.run().unwrap();
}

const HTML: &str = r#"
<!doctype html>
<html>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>
"#;
```
</details>

~~MSHTML works, but we must wait for an event loop iteration by using [`webview.step()`](https://docs.rs/web-view/0.5.4/web_view/struct.WebView.html#method.step), or the JS execution will fail and crash the app.~~
**Edit:** Update: this issue is now fixed in webview 0.6

<details><summary>Show Case</summary>

```rs
use web_view::*;

fn main() {
    let webview = web_view::builder()
        .title("Timer example")
        .content(Content::Html(HTML))
        .size(800, 600)
        .resizable(true)
        .debug(true)
        .user_data(0)
        .invoke_handler(|webview, arg| {
            match arg {
                "test" => webview.eval("test()")?,
                _ => unimplemented!()
            };
            Ok(())
        })
        .build()
        .unwrap();
        
    webview.handle().dispatch(|webview| {
        // we must wait one itteration of the even loop before executing js.
        webview.step().unwrap();
        webview.eval("test()")
    }).unwrap();

    webview.run().unwrap();
}

const HTML: &str = r#"
<!doctype html>
<html>
    <body>
        <h1>Hello World!</h1>
        <button onclick="external.invoke('test')">test</button>
    </body>
    <script>
        function test () {
            alert('Hi there!')
        }
    </script>
</html>
"#;
```
</details>

The new webview rewrite adds an [init](https://github.com/zserge/webview/blob/webview-x/webview.h#L87) method that will solve these problems, but there is no ETA.

The relevant code in tauri is [here](https://github.com/tauri-apps/tauri/blob/dev/tauri/src/app/runner.rs#L103)

I've only been able to test this on my machine, so others could have different experiences.

**Comment by BenoitRanque** [comment]
Workarround being discussed at #197

**Comment by nothingismagick** [comment]
FYI - the upstream zserge/webview has been detached from boscop/web-view. So that ETA you mentioned is something that we will probably never see in the near future. 

See here:
https://github.com/Boscop/web-view/tree/master/webview-sys

**Comment by BenoitRanque** [comment]
Thanks! Aparently there is an init method for edge webview [here](https://github.com/Boscop/web-view/blob/master/webview-sys/webview_edge.cpp#L303) that runs [here](https://github.com/Boscop/web-view/blob/master/webview-sys/webview_edge.cpp#L287), but I don't know if that is usable yet. Will do some more testing and report any findings here

**Comment by nothingismagick** [comment]
@BenoitRanque - is this still happening?

**Comment by tensor-programming** [comment]
I honestly believe this was resolved in webview 0.6.

**Comment by lucasfernog** [comment]
I will try it later tonight or tomorrow.

**Comment by BenoitRanque** [comment]
I'll redo my tests later tonight, with the latests webview. Will post update here

**Comment by BenoitRanque** [comment]
Update: the issue persists in webview 0.6 when using edge.

Good news however: the issue does no long exist when using MSHTML

**Comment by tensor-programming** [comment]
This should be an issue on webview not tauri. There isn't much that we can do from our side of the fence about this.  

If I had to guess as to whats going on, I would guess that the threading isn't perfect between the webview thread and the rust main thread.  If you run this code multiple times, you will eventually get a program that renders all of the elements.  

![timer](https://user-images.githubusercontent.com/22513880/72231513-e101ba80-3589-11ea-85bb-35ee70884c20.png)

**Comment by BenoitRanque** [comment]
> 
> 
> This should be an issue on webview not tauri. There isn't much that we can do from our side of the fence about this.
> 
> If I had to guess as to whats going on, I would guess that the threading isn't perfect between the webview thread and the rust main thread. If you run this code multiple times, you will eventually get a program that renders all of the elements.
> 
> ![timer](https://user-images.githubusercontent.com/22513880/72231513-e101ba80-3589-11ea-85bb-35ee70884c20.png)

I was thinking this may be because webview uses async js execution for edge. See source [here](https://github.com/Boscop/web-view/blob/master/webview-sys/webview_edge.cpp#L308) and docs [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.invokescriptasync)

**Comment by tensor-programming** [comment]
Regardless of whether or not its due to the async execution, this exercise reveals yet another flaw in the edge implementation.  When you run this on MSHTML, the other elements in the list of 1000 appear almost instantly but when you run it with edge, they appear one at a time and take at least .5 seconds to render.
