### ISSUE TITLE
Startup to crash under Windows

### ISSUE THREAD

**Issue by wsw0108** [tauri-apps/tauri#2867]
### **Describe the bug**
Installed app startup to crash under Windows 10.

### **To Reproduce**
1. clone https://github.com/wsw0108/tauri-test-app
2. yarn tauri build
3. install the release bundle msi
4. launch it
5. see crash

### **Expected behavior**
run without crash as `yarn tauri dev`.

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 95.0.1020.44

Node.js environment
  Node.js - 14.17.4
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  yarn - 1.22.15

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/.git
/build
/config
/node_modules
/public
/resources
/scripts
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
  bundler - Webpack
```

**Comment by amrbashir** [comment]
Can you get a stacktrace ? what happens when your run it from the command line ? what if you run the built exe from `target/release` folder ? can you try building in debug mode `yarn tauri build --debug` and see if it crashes ?

**Comment by wsw0108** [comment]
`yarn tauri build --debug` and then run from `target/debug` folder is ok, but with a conhost window.
run from `target/release` also crash.
If run exe from `target/release` from command line, no output to console.

Differences between debug and release:
```
PS E:\GitHub\tauri-test-app> file .\src-tauri\target\debug\tauri-test-app.exe
.\src-tauri\target\debug\tauri-test-app.exe; PE32+ executable for MS Windows (console) Mono/.Net assembly
PS E:\GitHub\tauri-test-app>
PS E:\GitHub\tauri-test-app> file .\src-tauri\target\release\tauri-test-app.exe
.\src-tauri\target\release\tauri-test-app.exe; PE32+ executable for MS Windows (GUI) Mono/.Net assembly
```
exe from debug mode is console;
exe from release mode is GUI;

**Comment by amrbashir** [comment]
that's expected but irrelevant to the issue but thanks for the info.

**Comment by lucasfernog** [comment]
I'm getting a `Segmentation fault` on your project.

This issue is fixed if I change `tauri = { version = "1.0.0-beta.8", features = ["api-all"] }` to `tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["api-all"] }`. I assume this is something that was fixed on the windows binding level on the tao repo. Please let me know if it still happens on your end with that change or on the next release.

**Comment by wsw0108** [comment]
I can not build success by replacing tauri with branch 'next', it requires 'edtion2021' and nightly cargo/rustc.

**Comment by amrbashir** [comment]
@wsw0108 your rust compiler is outdated, rust edition2021 has been stable since rustc 1.56
run `rustup update stable`

**Comment by wsw0108** [comment]
Thanks, this resolve the problem.

**Comment by NicolaSpadari** [comment]
Bumping this because I have the exact same issue, except updating rust doesn't solve the issue. Instead, I get this error:

```
 app:spawn Running "D:\Projects\vite-tauri\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri build" +0ms

    Updating git repository `https://github.com/tauri-apps/tauri`
error: failed to select a version for `tauri`.
    ... required by package `vite-tauri v1.0.3 (D:\Projects\vite-tauri\src-tauri)`
versions that meet the requirements `*` are: 1.0.0-beta.8

the package `vite-tauri` depends on `tauri`, with features: `all` but `tauri` does not have these features.


failed to select a version for `tauri` which could resolve this conflict
Error: failed to build app

Caused by:
    Result of `cargo build` operation was unsuccessful: exit code: 101

 app:spawn Command "D:\Projects\vite-tauri\node_modules\@tauri-apps\cli\bin\tauri-cli.exe" failed with exit code: 1 +0ms
```

My `dependencies` block:
```toml
[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
# tauri = { version = "1.0.0-beta.8", features = ["http-all", "path-all", "shell-all"] }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["shell-all"] }
```

Running the app in debug mode works but opens the console, running it without debug mode causes instant crash on startup.

**Comment by Heyh520** [comment]
I'm also getting crashes when I run exe after packing, my rustc version is 1.81.0
