### ISSUE TITLE
[bug] Crashing app appearance after Windows Remote Desktop connection

### ISSUE THREAD

**Issue by sgmm0hammad** [tauri-apps/tauri#6199]
### Describe the bug

App appearance looks like the below screenshots before and after the Windows Remote Desktop connection. I guess the screen resolution changes caused this behavior somehow.

**Before**
![Screenshot 2023-01-25 193523](https://user-images.githubusercontent.com/25132694/216810831-d1dd9823-90ba-4074-817a-aba47d3a5d4b.png)

**After**
![Screenshot 2023-01-25 193300](https://user-images.githubusercontent.com/25132694/216810851-8186c25a-3458-4091-b347-4c25f13ba9d1.png)

**After (Developers Tools - "html"  tag inspection)**
![Screenshot 2023-01-25 193238](https://user-images.githubusercontent.com/25132694/216810910-f129c237-9f03-4c2e-9b90-423313376621.png)
As you can see, "html" tag doesn't fill the whole page.

### Reproduction

1. Run the Tauri app
2. Connect via Windows Remote Desktop from another computer to the computer that running the Tauri app

### Platform and versions

Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 109.0.1518.70
  › MSVC: 
      - Visual Studio Build Tools 2019
  › Node.js: 16.13.2
  › npm: 8.5.4
  › pnpm: 7.19.0
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

**Comment by amrbashir** [comment]
does it get fixed if you resize the app by 1px at least?

**Comment by sgmm0hammad** [comment]
> does it get fixed if you resize the app by 1px at least?

Yes it fixed by resizing

**Comment by amrbashir** [comment]
could you try adding this to your `Cargo.toml`
```toml
[patch.crates-io]
wry = { git = "https://github.com/tauri-apps/wry", branch = "fix/windows/resize-on-dpi-theme-changes" }
```
then run `cargo update` inside `src-tauri` and see if the issue is fixed or not

**Comment by sgmm0hammad** [comment]
> could you try adding this to your `Cargo.toml`
> 
> ```toml
> [patch.crates-io]
> wry = { git = "https://github.com/tauri-apps/wry", branch = "fix/windows/resize-on-dpi-theme-changes" }
> ```
> 
> then run `cargo update` inside `src-tauri` and see if the issue is fixed or not

it doesn't fix, thank you anyway

**Comment by amrbashir** [comment]
could you try again? this time it should spam the console with logs, try to recreate the bug quickly so the logs are smaller and easier to parse then post them here.

**Comment by sgmm0hammad** [comment]
I tried again but didn't see logs. I realized a warning after trying to update the Cargo again.
```
warning: Patch `wry v0.24.1 (https://github.com/tauri-apps/wry?branch=fix/windows/resize-on-dpi-theme-changes#d9dd4d18)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
```
It seems was my fault, really sorry. I tried to solve it but I couldn't, I'm not a Rust developer. 
would you help me, please?

**Comment by amrbashir** [comment]
Ah that was my fault, could you try running `cargo update` again?

**Comment by sgmm0hammad** [comment]
I got this error
```
error[E0308]: mismatched types
    --> C:\Users\HP\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.12.2\src\lib.rs:3015:7
     |
3015 | /       protocol(&HttpRequestWrapper::from(wry_request).0)
3016 | |         .map(|tauri_response| HttpResponseWrapper::from(tauri_response).0)
3017 | |         .map_err(|_| wry::Error::InitScriptError)
     | |_________________________________________________^ expected enum `Cow`, found struct `Vec`
     |
     = note: expected enum `Result<wry::http::Response<Cow<'static, [u8]>>, _>`
                found enum `Result<wry::http::Response<Vec<u8>>, _>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `tauri-runtime-wry` due to previous error
```

**Comment by amrbashir** [comment]
alright, give it another go, it should compile fine now. See if the webview resizes correctly, if not, try to get the relevant logs.

**Comment by sgmm0hammad** [comment]
thank you, these are the logs:

```
WM_KILLFOCUS
WM_IME_SETCONTEXT
WM_NCACTIVATE
WM_ACTIVATE
WM_ACTIVATEAPP

------------------------------- I connect via the Windows Remote Desktop and then :

0x2E4
WM_WINDOWPOSCHANGING
0x2E0
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_GETICON
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_MOVE
WM_SIZE
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_PAINT
0x320
WM_TIMECHANGE
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
0x320
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_WINDOWPOSCHANGED
WM_TIMECHANGE
WM_WINDOWPOSCHANGING
WM_WINDOWPOSCHANGED
WM_MOVE
WM_DISPLAYCHANGE
WM_SYSCOLORCHANGE
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
0x320
WM_WINDOWPOSCHANGING
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_DEVICECHANGE
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WINDOWPOSCHANGING
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_DEVICECHANGE
WM_DEVICECHANGE
0xC0D4
WM_GETICON
WM_DEVICECHANGE
WM_DEVICECHANGE
WM_DEVICECHANGE
WM_DEVICECHANGE
WM_SETCURSOR
WM_NCMOUSEMOVE
WM_NCMOUSELEAVE
WM_NCHITTEST
WM_SETCURSOR
WM_NCMOUSEMOVE
WM_NCMOUSELEAVE
WM_NCHITTEST
WM_SETCURSOR
WM_MOUSEMOVE
WM_MOUSELEAVE
```

![Screenshot 2023-02-14 132145](https://user-images.githubusercontent.com/25132694/218701456-d1c3b2ee-8825-4957-b7ce-70d78a9a037f.png)

**Comment by amrbashir** [comment]
Please run `cargo update` and try again, if issue still persists, there should be some new logs, please post them here. Thanks for your patience

**Comment by sgmm0hammad** [comment]
it doesn't fix yet, and the logs are: 

```
WM_KILLFOCUS
WM_IME_SETCONTEXT
WM_NCACTIVATE
WM_ACTIVATE
WM_ACTIVATEAPP

// --------- bug starts here

0x2E4
WM_WINDOWPOSCHANGING
0x2E0
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_GETICON
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_MOVE
WM_SIZE
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_PAINT
0x320
WM_WINDOWPOSCHANGING
WM_TIMECHANGE
0x320
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_TIMECHANGE
WM_DISPLAYCHANGE
WM_SYSCOLORCHANGE
0x320
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WINDOWPOSCHANGING
WM_DISPLAYCHANGE
WM_WINDOWPOSCHANGING
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WINDOWPOSCHANGING
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WININICHANGE
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
0xC0D4
WM_DEVICECHANGE
WM_DEVICECHANGE
```

**Comment by amrbashir** [comment]
these logs show that you are not using the latest changes I pushed, run `cargo update` inside `src-tauri` before running `tauri dev` or `tauri build`

**Comment by sgmm0hammad** [comment]
I'm sure that I updated the Cargo last time ...,  anyway I got new logs this time.

```
WM_KILLFOCUS
WM_IME_SETCONTEXT
WM_NCACTIVATE
WM_ACTIVATE
WM_ACTIVATEAPP
0x2E4
WM_WINDOWPOSCHANGING
0x2E0
  WINDOW: left: 0, top: 0, right: 750, bottom: 625
  WEBVIEW BEFORE: left: 0, top: 0, right: 750, bottom: 625
  WEBVIEW AFTER: left: 0, top: 0, right: 750, bottom: 625
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_GETICON
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_MOVE
WM_SIZE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 750, bottom: 625
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_PAINT
0x320
WM_WINDOWPOSCHANGING
WM_TIMECHANGE
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
0x320
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_TIMECHANGE
WM_DISPLAYCHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_SYSCOLORCHANGE
0x320
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_DISPLAYCHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_WINDOWPOSCHANGING
WM_WINDOWPOSCHANGING
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WINDOWPOSCHANGING
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
0xC0D4
WM_DEVICECHANGE
WM_DEVICECHANGE
WM_DEVICECHANGE
WM_DEVICECHANGE
```

**Comment by amrbashir** [comment]
Pushed another attempt, run `cargo update` and see if it is fixed, hopefully it works, otherwise I am out of solutions.

**Comment by sgmm0hammad** [comment]
it didn't fix, I put the logs here anyway. I greatly appreciate the time you spent trying to fix the bug.

```
WM_ACTIVATE
WM_ACTIVATEAPP
0x2E4
WM_WINDOWPOSCHANGING
0x2E0
  WINDOW: left: 0, top: 0, right: 750, bottom: 625
  WEBVIEW BEFORE: left: 0, top: 0, right: 750, bottom: 625
  WEBVIEW AFTER: left: 0, top: 0, right: 750, bottom: 625
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_GETICON
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 750, bottom: 625
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_MOVE
WM_SIZE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_PAINT
0x320
WM_WINDOWPOSCHANGING
WM_TIMECHANGE
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x320
WM_TIMECHANGE
WM_WINDOWPOSCHANGING
WM_DISPLAYCHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_SYSCOLORCHANGE
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x320
WM_WINDOWPOSCHANGING
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_WINDOWPOSCHANGING
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
WM_WININICHANGE
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0x31A
WM_WINDOWPOSCHANGING
WM_NCCALCSIZE
WM_NCPAINT
WM_ERASEBKGND
WM_WINDOWPOSCHANGED
  WINDOW: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW BEFORE: left: 0, top: 0, right: 600, bottom: 500
  WEBVIEW AFTER: left: 0, top: 0, right: 600, bottom: 500
0xC0D4
WM_GETICON
WM_DEVICECHANGE
WM_DEVICECHANGE
WM_DEVICECHANGE
WM_DEVICECHANGE
```
