### ISSUE TITLE
[bug] Android - unable to build on a particular env

### ISSUE THREAD

**Issue by doums** [tauri-apps/tauri#6367]
### Describe the bug

Hi, first, it's not a bug, but more a question. And it's **specific** to the particular [fdroid](https://f-droid.org) build environment. I'm trying to get an app included in fdroid store.
During the build process, it removes the provided `gradlew` binary located at `src-tauri/gen/android/app_project/gradlew` because it does not trust it, and instead it wants to use its own one. This can't be disabled. So if there are gradle commands to run during the build, we have to use the one provided by fdroid env, and we can't rely on the one provided by tauri android commands, which live in different location.
The thing is, `tauri android build` command rely on the one located at `src-tauri/gen/android/app_project/gradlew`. So the build fails with a `No such file or directory` error.
So my questions is:\
There is a way to work around that? Like building using classic gradle binary family without to have invoking the `tauri android build` command?

For reference, this is the build pipeline failing https://gitlab.com/doums/fdroid-data/-/jobs/3831578568

### Platform and versions

Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 18.13.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.2
  › @tauri-apps/api [NPM]: 2.0.0-alpha.0
  › tauri [RUST]: 2.0.0-alpha.3,
  › tauri-build [RUST]: 2.0.0-alpha.1,
  › tao [RUST]: 0.17.0,
  › wry [RUST]: 0.26.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:9000/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ public
  ├─ src-tauri
  ├─ .idea
  ├─ .storybook
  ├─ node_modules
  ├─ src
  └─ dist

**Comment by doums** [comment]
Hey, any news ? There is any way to build without invoking `tauri android build` command?
What does `tauri android build` command exactly ?

**Comment by amrbashir** [comment]
I assume that `gradlew` is available through `PATH` if so this PR https://github.com/tauri-apps/tauri-mobile/pull/111 should fix it.

**Comment by doums** [comment]
Hey, cool! But Im not sure how can I pull this changes in our project?  Using the `next` branch of tauri?

**Comment by amrbashir** [comment]
I think this snippet should do it
```toml
[patch.crates-io]
tauri-mobile = "https://github.com/tauri-apps/tauri-mobile"
```
then run `cargo update` inside `src-tauri`

**Comment by doums** [comment]
Hey thx, but this does not fix the issue because I think `gradlew` does not exist in the fdroid build server. And this is normal. As I understand gradle wrapper (`gradlew`), it is meant to provide a ready to use gradle setup without having to follow manual installation processes. So it's intended to be included within project files (which is the case with tauri mobile project) and not intended to be provided as global binary by the environment.
Based on that `tauri android build` should first try with `gradlew`, and if it does not exist, it should fallback on `gradle` binary instead (from PATH). It might require performing version check as well.

**Comment by amrbashir** [comment]
thanks, I was under the assumption that the global binary was also called `gradlew`, I will open a PR to fix it

**Comment by amrbashir** [comment]
https://github.com/tauri-apps/tauri-mobile/pull/113 should fix this 
and now I am realizing the snippet I mentioned in my last comment wasn't entirely true https://github.com/tauri-apps/tauri/issues/6367#issuecomment-1460122249 if you want to test the changes, you need to clone tauri repo, add the patch from the earlier snippet in `tooling/cli/Cargo.toml` then install the cli 
```
cargo install --path tooling/cli
```
