### ISSUE TITLE
[bug]  window.__TAURI_IPC__ is not a function

### ISSUE THREAD

**Issue by Arian94** [tauri-apps/tauri#6396]
### Describe the bug

Upgraded tauri and everything both on Rust crates and Yarn packages. Upgraded Rust from 1.65 to 1.67.1.

Tried to build in dev mode, the tao window will not open. It says tauri app is not responding. So I force quit it.
Tried to build in produciton mode and same thing happened.
Tried to serve it and used a browser, it shows the app window but in the Console it says  window.__TAURI_IPC__ is not a function.

What's wrong? Everything was fine before the update. Please, be more consistent with the updates. Every time there is an issue and I can't figure it out anymore. I have an app on Snap Store and it's getting harder and harder to develop.

### Platform and versions

No error. compiles with no error.

tauri = {version = "1.2.4",}

**Comment by amrbashir** [comment]
Please make a reproduction case or steps to reproduce or at least the affected repo. This makes it easier for us to find and fix the bug. And please fill out the info section properly using `tauri info`. 

I will re-open once the needed info is provided.

**Comment by amrbashir** [comment]
> Tried to serve it and used a browser, it shows the app window but in the Console it says window.TAURI_IPC is not a function.

This is expected since you opened your app in a *Browser*. 

I need a reproduction for the `not responding` issue.

**Comment by Arian94** [comment]
`tauri info:`
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 18.14.2
  › npm: 9.5.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › framework: React
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ .git
  ├─ src-tauri
  ├─ node_modules
  └─ src
Done in 34.13s.


I upgraded Rust from 1.65 to 1.67.1 and tauri from 1.1.1 to 1.2.4.
The I enter `yarn tauri dev`. A window opens up in the deck but it says the app is not responding.

**Comment by amrbashir** [comment]
> I upgraded Rust from 1.65 to 1.67.1 and tauri from 1.1.1 to 1.2.4.
> The I enter yarn tauri dev. A window opens up in the deck but it says the app is not responding.

This is still not enough, I need steps to reproduce or a minimal reproduction repo. You can also try creating a new app using `create-tauri-app` and see if it hangs or not.

**Comment by Arian94** [comment]
The issue is actually with my code!! Inside the `setup` method I've replaced `thread::spawn` with `thread::scope` and the thing is it cannot return:

### Before:
```rust
tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
             // some functions,
        ])
        .system_tray(tray)
        .setup(move |app| {
             thread::spawn(move || {
                // some code
            });

            Ok(())
        });
```

### After:
```rust
tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
             // some functions,
        ])
        .system_tray(tray)
        .setup(move |app| {
            thread::scope(|s| {
                s.spawn(|| {
                    // some code
                });
            });
            
           //! THIS WILL NEVER GET TO THE NEXT LINE.
            Ok(())
        });
```
