### ISSUE TITLE
[feat] Can Tauri be visible in all workspaces of macOS?

### ISSUE THREAD

**Issue by ninetyeights** [tauri-apps/tauri#6589]
### Describe the problem

![CleanShot 2023-03-29 at 21 39 37](https://user-images.githubusercontent.com/78558736/228705932-f3df0f7e-1a11-4ec0-9a86-dfe8eb4310d8.gif)

I've searched for a lot of ways to implement a window that shows in all workspaces when switching workspaces in macOS, similar to the settings in Electron, as in the screenshot below, but I haven't found a way to do it, and I wonder if there's another way to do it?
![CleanShot 2023-03-29 at 21 28 22](https://user-images.githubusercontent.com/78558736/228704470-f012817d-019d-41d8-aa7f-c82b4305e718.png)

### Describe the solution you'd like

Is it possible to add this setting, or is there another solution?

**Comment by FabianLars** [comment]
This was added to Tao in January: https://github.com/tauri-apps/tao/pull/666. Since this was released in tao 0.15.9/0.16.0 (tauri 1.x is locked to 0.16) this could be added in a potential 1.4 release :)

If you need it _now_ you'd have to replicate the PR in Rust in your own code.

**Comment by emidoots** [comment]
We're soon to use Tauri in production at Sourcegraph; and would love this feature. I know +1 comments aren't useful, but figured I'd mention it just in case

**Comment by kris-ava** [comment]
This seems to have been in tao since a few versions, but the API never got propagated all the way to Tauri. Is there any update on this?

**Comment by threeseed** [comment]
@wusyong @krzykro2  .. I just tried this out and it doesn't appear to work.

I have uploaded a minimal test case [here](https://github.com/harana-oss/tauri-6589).

The registered hot key toggles the window on one Mac space. But not on any other.

**Comment by T31K** [comment]
Any update on this?

edit: seems like it was added to tauri `2.0.0`. any way to use it on older versions?

**Comment by ninetyeights** [comment]
> Any update on this?
> 
> edit: seems like it was added to tauri `2.0.0`. any way to use it on older versions?

Yes, I implemented it using Cocoa’s native functions. Here I have uploaded a test case for your reference.
https://gist.github.com/ninetyeights/ddfbe532f5485b761dc5db122e26cfa9

**Comment by T31K** [comment]
lovely mate, cheers!
tested and working 👍🏻  
@ninetyeights

**Comment by Yiork** [comment]
it works perfectly , thanks you @ninetyeights

**Comment by TamasBarta** [comment]
Please reopen this. 2.0 is alpha software. This issue is not fixed, because it is not scheduled to be released in a stable version.
