### ISSUE TITLE
[bug] Using the Weasel input method in the always-on-top window will get stuck

### ISSUE THREAD

**Issue by Pylogmon** [tauri-apps/tauri#6879]
### Describe the bug

I found that using the Rime Input Method Engine based [Weasel input method](https://github.com/rime/weasel) in my tauri application causes the window to get stuck, I tested other applications and no such problem occurs, only in the tauri application, so I think it might be a tauri problem.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 112.0.1722.68
  › MSVC: 
  › Node.js: 19.9.0
  › npm: 9.6.3
  › pnpm: 8.4.0
  › yarn: Not installed!
  › rustup: 1.26.0
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3 (outdated, latest: 1.3.0)
```

### Additional context

https://user-images.githubusercontent.com/59004461/236631795-f1f5002d-bd27-4da8-9933-a3b92ca5c612.mp4

Since I couldn't get the window to un-top when it was stuck, I tested it by using PowerToy to make the window top, and it looked like the input method was blocked, and the previous input would appear quickly when the top was un-topped.

**Comment by wusyong** [comment]
What about default IME? Does it work fine for you?
And it's better to bring a minimum repo or step to reproduce. It can help us a lot to narrow the scope.

**Comment by Pylogmon** [comment]
> What about default IME? Does it work fine for you?

Yes, it works fine

**Comment by Pylogmon** [comment]
My Step:

1. pnpm create tauri-app
2. pnpm install
3. Edit `tauri.conf.json` to make window always-on-top(or make window on-top by PowerToy later)
4. pnpm tauri dev
5. Input something using Weasel,then window get stuck

**Comment by Pylogmon** [comment]
This problem has been fixed by Weasel, It seems that this is not a problem with Tauri.

**Comment by Blushyes** [comment]
> This problem has been fixed by Weasel, It seems that this is not a problem with Tauri.

How did you manage to fix it? I've recently encountered the same problem.

**Comment by Blushyes** [comment]
> is problem has been fixed by Weasel, It seems that this is not a problem with Tauri.

How did you resolve this issue back then?

**Comment by uqiu** [comment]
![image](https://github.com/user-attachments/assets/eee01148-ea92-4da2-a10e-1a164ba4ab3f)
This is my version of RIME, and I still have this issue.

**Comment by uqiu** [comment]
@Blushyes 
got some solution?
