### ISSUE TITLE
[bug] Tauri 1.3.1 Error: Cannot find module '@tauri-apps/cli-win32-x64-msvc'

### ISSUE THREAD

**Issue by tance77** [tauri-apps/tauri#7087]
### Describe the bug

When building the application in version 1.3.1 on different systems, such as a CI server for Windows and Mac, the build process encounters errors related to system architecture detection. The issue occurs specifically in version 1.3.1 and does not manifest in version 1.3.0, even with identical code. It is worth noting that while the build succeeds on a local M2 Mac using version 1.3.1, it fails on a VM Windows running on the same M2 Mac. The VM is running Windows 11.

### Expected behavior

It should properly include this package '@tauri-apps/cli-win32-x64-msvc'.

### Platform and versions

```text
Mac:

› OS: Mac OS 13.3.1 X64
  › Node.js: 18.16.0
  › npm: 9.5.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: 1.67-aarch64-apple-darwin 

Window VM:
Windows 11

CI Server: 
We just use the basic github servers

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
```

### Stack trace

```sh
C:\Users\genericuser\Desktop\app\node_modules\@tauri-apps\cli\index.js:250
    throw loadError
    ^
Error: Cannot find module '@tauri-apps/cli-win32-x64-msvc'
Require stack:
- C:\Users\genericuser\Desktop\app\node_modules\@tauri-apps\cli\index.js
- C:\Users\genericuser\Desktop\app\node_modules\@tauri-apps\cli\main.js
- C:\Users\genericuser\Desktop\app\node_modules\@tauri-apps\cli\tauri.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\genericuser\Desktop\app\node_modules\@tauri-apps\cli\index.js:72:29)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
```

**Comment by FabianLars** [comment]
It may sound stupid but did you try deleting the node_modules folder and re-installing it? If 1.3.0 worked than 1.3.1 should work just the same as there were no changes that would affect this at all.

Also since you're using an arm vm (at least i think so since your host is arm) it may stay a bit wonky since we don't have prebuilt win+arm clis yet.
Which is also what confuses me here, because the cli packages uses the arch of the nodejs installation to select which subpackage to run (which in this case suggest your nodejs installation is x64) and i _thought_ the package.json's `arch` field is resolved in the same way but apparently not, otherwise it would have installed the x64 subpackage (in case re-installing doesn't help)

Anyway, if it doesn't work, can you try running this?
```
cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch cli/windows-arm64 --no-default-features --features native-tls-vendored
```
In case installation is successful you can then use the cargo cli like `cargo tauri dev`

**Comment by shurkanTwo** [comment]
This has helped to fix the issue for me.
Just run this in your project directory:
`npm install @tauri-apps/cli-win32-x64-msvc@2.0.0-alpha.9 `
(You might want to choose a different version: https://libraries.io/npm/@tauri-apps%2Fcli-win32-x64-msvc)

**Comment by nimeshmaharjan1** [comment]
Still not working
`mahar@Predator MINGW64 ~/projects/tauri-app
$ npm run tauri

> tauri-app@0.0.0 tauri
> tauri

C:\Users\mahar\projects\tauri-app\node_modules\@tauri-apps\cli\index.js:250
    throw loadError
    ^

Error: The specified module could not be found.
\\?\C:\Users\mahar\projects\tauri-app\node_modules\@tauri-apps\cli\node_modules\@tauri-apps\cli-win32-x64-msvc\cli.win32-x64-msvc.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\mahar\projects\tauri-app\node_modules\@tauri-apps\cli\index.js:72:29)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.11.0`

> This has helped to fix the issue for me. Just run this in your project directory: `npm install @tauri-apps/cli-win32-x64-msvc@2.0.0-alpha.9 ` (You might want to choose a different version: https://libraries.io/npm/@tauri-apps%2Fcli-win32-x64-msvc)

**Comment by Silomalo** [comment]
I have a similar issue in a git-workflow, am trying to build for multi-platform: 
locally i can build the application well:

`name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn' # Set this to npm, yarn or pnpm.

      - name: Install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: yarn install # Change this to npm, yarn or pnpm.

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'App Name v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false`

**Comment by memark** [comment]
We're getting this error in our Gitlab CI on Windows with @tauri-apps/cli@1.6.0.

Was there ever a solution apart from "upgrading to 1.3.1"?
