### ISSUE TITLE
[bug] Tauri does not detect system theme preference on Linux

### ISSUE THREAD

**Issue by mirkobrombin** [tauri-apps/tauri#9427]
### Describe the bug

In my application I use the `prefers-color-scheme` media to change the color scheme of my app. It works on Chrome/Firefox/Epipahny (on Linux) but not on Tauri. I tried listening to `tauri://theme-changed` for what Tauri sees but the result is always `light` even if dark mode is enabled in GNOME.

### Reproduction

1. Make a new Tauri project using V1
2. Listen to `tauri://theme-changed` for theme changes or directly print the `appWindow.theme()` promise
3. See that `light` returns even if a dark theme is active in the system

### Expected behavior

I expect it to return `dark` if the system is using a dark theme.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Linux Unknown X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.19.0
    - pnpm: 8.15.5
    - npm: 9.2.0

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.8
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Additional context

For instance, I am using the default theme (Adwaita) in GNOME 44.8. I also managed to reproduce the same issue using Tauri v2.

**Comment by i-c-b** [comment]
The `tauri://theme-changed` event isn't supported for Linux as it listens for [`tao::event::WindowEvent::ThemeChanged`](<https://docs.rs/tao/0.16.8/tao/event/enum.WindowEvent.html#variant.ThemeChanged>).

I wasn't able to replicate the theme detection problem with Adwaita on Ubuntu 22.04.4 (GNOME 42) and Ubuntu 23.10 (GNOME 45) after installing `gnome-tweaks` to change from Yaru to Adwaita (and Adwaita-dark). In my tests, the dark theme applied correctly.

If possible, can you install `neofetch` (or an alternative that can read [`gtk-theme-name`](<https://docs.gtk.org/gtk3/property.Settings.gtk-theme-name.html>)) and share what the `Theme` value is? The value doesn't always match the value set by `gnome-control-center`, as shown in the screenshots attached to the end of this message.

The WebKitGTK implementation discussed in <https://bugs.webkit.org/show_bug.cgi?id=197947> reads the [`GTK_THEME` environment variable or the `gtk-theme-name` GTK setting](<https://github.com/WebKit/WebKit/blob/052c7b2a782b865f1922a7c9a691799aa815d306/Source/WebKit/UIProcess/API/gtk/PageClientImpl.cpp#L602-L619>) and expects a dark theme variant to end with `-dark`, `-Dark`, or `:dark`.

[1_light_yaru-light_yaru-light_light](https://github.com/tauri-apps/tauri/assets/133848861/641d70ed-c307-4f32-9009-2b7f45be436f)
[2_dark_yaru-dark_yaru-dark_dark](https://github.com/tauri-apps/tauri/assets/133848861/e3fa57e4-fc86-4559-b090-b42b3934c3f2)
[3_dark_adwaita-light_adwaita-light_light](https://github.com/tauri-apps/tauri/assets/133848861/956230fa-dadb-470e-b367-e36afd92c057)
[4_light_adwaita-dark_adwaita-dark_dark](https://github.com/tauri-apps/tauri/assets/133848861/fc1281b2-ec43-4417-841b-a5dffab32a05)

**Comment by Megamannen** [comment]
Yeah, it checks the "legacy theme" setting. I have dark mode in Gnome 44 but I got light theme in Tauri app until I changed this

![bild](https://github.com/tauri-apps/tauri/assets/19424456/e171b5e1-a8d2-4b51-9fda-1a4f7473c91e)

**Comment by mirkobrombin** [comment]
> The `tauri://theme-changed` event isn't supported for Linux as it listens for [`tao::event::WindowEvent::ThemeChanged`](https://docs.rs/tao/0.16.8/tao/event/enum.WindowEvent.html#variant.ThemeChanged).
> 
> I wasn't able to replicate the theme detection problem with Adwaita on Ubuntu 22.04.4 (GNOME 42) and Ubuntu 23.10 (GNOME 45) after installing `gnome-tweaks` to change from Yaru to Adwaita (and Adwaita-dark). In my tests, the dark theme applied correctly.
> 
> If possible, can you install `neofetch` (or an alternative that can read [`gtk-theme-name`](https://docs.gtk.org/gtk3/property.Settings.gtk-theme-name.html)) and share what the `Theme` value is? The value doesn't always match the value set by `gnome-control-center`, as shown in the screenshots attached to the end of this message.
> 
> The WebKitGTK implementation discussed in https://bugs.webkit.org/show_bug.cgi?id=197947 reads the [`GTK_THEME` environment variable or the `gtk-theme-name` GTK setting](https://github.com/WebKit/WebKit/blob/052c7b2a782b865f1922a7c9a691799aa815d306/Source/WebKit/UIProcess/API/gtk/PageClientImpl.cpp#L602-L619) and expects a dark theme variant to end with `-dark`, `-Dark`, or `:dark`.
> 
> [1_light_yaru-light_yaru-light_light](https://github.com/tauri-apps/tauri/assets/133848861/641d70ed-c307-4f32-9009-2b7f45be436f) [2_dark_yaru-dark_yaru-dark_dark](https://github.com/tauri-apps/tauri/assets/133848861/e3fa57e4-fc86-4559-b090-b42b3934c3f2) [3_dark_adwaita-light_adwaita-light_light](https://github.com/tauri-apps/tauri/assets/133848861/956230fa-dadb-470e-b367-e36afd92c057) [4_light_adwaita-dark_adwaita-dark_dark](https://github.com/tauri-apps/tauri/assets/133848861/fc1281b2-ec43-4417-841b-a5dffab32a05)

In many recent distributions the `GTK_THEME` env var is not set.

The theme found by neofetch is `Adwaita` which does not turn to `Adwaita-dark` when enabling dark theme in GNOME.

From what I understand, new versions of GNOME (and KDE) now use the freedesktop standard `org.freedesktop.appearance.color-scheme` to identify the system preference, rather than reading the theme name:

> The new preference is defined in the settings portal as the [org.freedesktop.appearance.color-scheme](https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.impl.portal.Settings.xml#L33-L45) key.
> 
> xdg-desktop-portal-gnome already [implements](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/12) this key (in the main branch, not in 41), and there are work-in-progress [elementary](https://github.com/elementary/settings-daemon/pull/38) and [KDE](https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/49) implementations.
> 
> This way it’s not tied to any particular desktop or toolkit — any application can access the settings portal via DBus and read the preference — so applications like Firefox have a canonical location to access the preference from instead of trying to guess it from GTK theme name. Being in the portal also means it’s accessible to Flatpak apps without opening any sandbox holes.
> 

Sources: 
- GNOME: https://blogs.gnome.org/alicem/2021/10/04/dark-style-preference/
- KDE: https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/52

**Comment by jokeyrhyme** [comment]
Yep, one approach could be to use the [ashpd](https://crates.io/crates/ashpd) crate (or bespoke D-Bus bindings maintained in tauri) to ask the [Settings portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html) for the freedesktop.org-standardised color-scheme value, and to also subscribe to changes to the color-scheme value

**Comment by MatthewScholefield** [comment]
I think this is solved via [tauri-plugin-theme](https://github.com/wyhaya/tauri-plugin-theme) right? I tried it and it now automatically follows the theme selector on GNOME.

**Comment by bukowa** [comment]
Can you check if you have the same problem using vanilla js? (without vue etc.)

**Comment by mirkobrombin** [comment]
It was a bit of a pain due to `javascriptcoregtk-4.0` no more supported in Vanilla OS (and Debian Sid, at least for amd64), anyway I managed to perform a test on a fedora container (which has access to the dbus instance in the host) and the problem still occurs even on a JS vanilla project. I specify that it would be best not to give too much weight to this last test given the particular setup, I can try to test in a VM on a distro that offers that dependency, but not immediately.

**Comment by Yanyan99999** [comment]
@MatthewScholefield which tauri version you use, i use tauri 1.5.3 and add tauri-plugin-theme, met issue:  .plugin(tauri_plugin_theme::init(tauri::generate_context!().config_mut()))
   |                                     ^^^^ not found in `tauri_plugin_theme` 
just want to ask have you ever met it?

**Comment by MatthewScholefield** [comment]
@Yanyan99999 See https://github.com/wyhaya/tauri-plugin-theme/issues/13#issuecomment-2300845486

Also though I'm using Tauri 2 which I think most people should start moving to anyways.

**Comment by xty** [comment]
> The WebKitGTK implementation discussed in https://bugs.webkit.org/show_bug.cgi?id=197947 reads the [`GTK_THEME` environment variable or the `gtk-theme-name` GTK setting](https://github.com/WebKit/WebKit/blob/052c7b2a782b865f1922a7c9a691799aa815d306/Source/WebKit/UIProcess/API/gtk/PageClientImpl.cpp#L602-L619) and expects a dark theme variant to end with `-dark`, `-Dark`, or `:dark`.

This [upstream PR](https://github.com/WebKit/WebKit/pull/32968) affecting the underlying implementation landed over a year ago. Has the issue here been resolved now?

> I think this is solved via [tauri-plugin-theme](https://github.com/wyhaya/tauri-plugin-theme) right? I tried it and it now automatically follows the theme selector on GNOME. 

Something as basic as `prefers-color-scheme` should work out of the box, not be left to plugins.

**Comment by Nishantdd** [comment]
@xty I'm creating a new project with tauri-v2 (2.9.4). This is how I'm using the theme api:
```javascript
    (async () => {
      if (theme !== "system") return root.classList.add(theme);
      const systemTheme = (await getCurrentWindow().theme()) ?? "dark";
      root.classList.add(systemTheme);

      unlisten = await getCurrentWindow().onThemeChanged(({ payload }) => {
        root.classList.remove("light", "dark");
        root.classList.add(payload ?? "dark");
      });
    })();
```
On Fedora 43 + GNOME, theme() returns light even when it's set to dark:
```bash
$ gsettings get org.gnome.desktop.interface color-scheme
> 'prefer-dark'

$ gsettings get org.gnome.desktop.interface gtk-theme
> 'Adwaita'
```

**Comment by FabianLars** [comment]
will be fixed in tauri v2.11 per https://github.com/tauri-apps/tao/pull/1141
