### ISSUE TITLE
[bug] thread 'main' has overflowed its stack (Windows 11 Tauri v2 beta)

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/tauri#9882]
### Describe the bug

Got `thread 'main' has overflowed its stack` error on Windows. (Also tried on Mac and Linux and there is no problem)

I was developing an app on Mac. When I try to migrate to Windows, I got this error.  

I have seen the same error message in other github issues, but I don't think it's the same problem.

### Reproduction

I made a minimum reproduction project here https://github.com/HuakunShen/tauri-win-stackoverflow

Some explanation in repo README as well.

I simply added a few official plugins, and 2 capability files.

For me the reproduction project won't run with `npm run tauri dev`. But if I run rust code with release mode it will run.

```bash
pnpm dev # start frontend dev server

# in another terminal
cd src-tauri
cargo run # this still gives stack overflow error
cargo run --release # this will run
```

If I simply remove 3 unused plugins from Cargo.toml it will run.

If I remove some capabilities it will run.

### Expected behavior

It should run.

### Full `tauri info` output

```text
❯ npm run tauri info

> tauri-win-stackoverflow@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 125.0.2535.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - pnpm: 9.1.2
    - yarn: 1.22.22
    - npm: 10.5.2
    - bun: 1.1.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.20
    - tauri-build [RUST]: 2.0.0-beta.16
    - wry [RUST]: 0.40.0
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.12
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
❯ pnpm tauri dev

> tauri-win-stackoverflow@0.0.0 tauri C:\Users\shenh\Desktop\tauri-win-stackoverflow
> tauri "dev"

    Running BeforeDevCommand (`pnpm dev`)

> tauri-win-stackoverflow@0.0.0 dev C:\Users\shenh\Desktop\tauri-win-stackoverflow
> vite


  VITE v5.2.11  ready in 130 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
    Info Watching C:\Users\shenh\Desktop\tauri-win-stackoverflow\src-tauri for changes...
   Compiling tauri-win-stackoverflow v0.0.0 (C:\Users\shenh\Desktop\tauri-win-stackoverflow\src-tauri)
error: failed to remove file `C:\Users\shenh\Desktop\tauri-win-stackoverflow\src-tauri\target\debug\tauri-win-stackoverflow.exe`

Caused by:
  Access is denied. (os error 5)
 ELIFECYCLE  Command failed with exit code 4294967295.
 ELIFECYCLE  Command failed with exit code 101
```

**Comment by amrbashir** [comment]
> If I simply remove 3 unused plugins from Cargo.toml it will run.
>
> If I remove some capabilities it will run.

Which plugins and which capabilities?

**Comment by HuakunShen** [comment]
> > If I simply remove 3 unused plugins from Cargo.toml it will run.
> > If I remove some capabilities it will run.
> 
> Which plugins and which capabilities?

@amrbashir 

It may differ on different computers. I tried on another Win11 and it can handle a few more capabilities than the first Win11 I experimented with. 

For example, doing any of the following will get rid of the stackoverflow error for me, but on your computer you may or may not need to remove a few more capabilities.

### 1. Remove remote urls from `capabilities/ext.json`
```json
    "remote": {
        "urls": [
            "http://localhost:1566/*",
            "http://localhost:*"
        ]
    },
```

### 2. Remove all fs permissions in  `capabilities/ext.json`

```json
"fs:allow-exists",
"fs:allow-stat",
"fs:read-all",
"fs:allow-mkdir",
"fs:allow-app-write",
"fs:allow-app-write-recursive",
"fs:allow-appcache-write",
"fs:allow-appcache-write-recursive",
"fs:allow-appconfig-write",
```

### 3. Remove all permissions in `capabilities/main.json`



I have tried to remove capabilities and plugins line by line to narrow down the cause but couldn't find a specific plugin causing this. They all work by themselves, but will stackoverflow when combined.

I think this is simply because the stack is full. 
I am not familiar with very low level system programming, but from what I know Windows has a default 1MB stack size, Mac and Linux have 8MB stack size. I guess this is why.

I have tried to increase stack size with env var and some other options but still couldn't get it working.

```ps
set RUSTFLAGS=-C link-args=/STACK:16777216
cargo run
```

**Comment by reyamir** [comment]
I got same error, but my cause is different, if I add more than around 10 commands, it will crash but not happening on my macos and linux devices

**Comment by HuakunShen** [comment]
> I got same error, but my cause is different, if I add more than around 10 commands, it will crash but not happening on my macos and linux devices

It's the same for me, I app also had ~30 commands. I didn't include them in the reproduction code for simplicity.

**Comment by HuakunShen** [comment]
@FabianLars Can you take a look on this? This has been blocking me for a month.

**Comment by HuakunShen** [comment]
Problem solved by increasing stack size.
I tried so many config/flags. This one works.

Add to `.cargo/config.toml`

```toml
[target.x86_64-pc-windows-msvc]
rustflags = [
	"-C", "link-arg=/STACK:8000000"
]

# 64 bit Mingw
[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "link-arg=-Wl,--stack,8000000"
]
```

Reference: https://users.rust-lang.org/t/stack-overflow-when-compiling-on-windows-10/50818/7

At first I thought there was something wrong with the code or plugins installed (e.g. infinite recursion, compatibility with windows). Then I realized Windows has a much smaller stack size than mac and linux. That's why it only overflows on Windows. 
As more rust code, plugins and permissions are added, the program is likely to stack overflow (on windows first).

**Comment by kikijiki** [comment]
I hit this too, in my case I just have 3 commands and some fs permissions.

I don't think this should be closed though, it's not normal and will leave a lot of people guessing what's wrong.
Maybe Tauri could use less stack memory by allocating more on the heap (`Box`)?

**Comment by HuakunShen** [comment]
> I hit this too, in my case I just have 3 commands and some fs permissions.
> 
> I don't think this should be closed though, it's not normal and will leave a lot of people guessing what's wrong. Maybe Tauri could use less stack memory by allocating more on the heap (`Box`)?

Makes sense, commands and plugins which are dynamically added could easily overflow the stack as the number grows. Ideally they should be allocated on heap.

I will reopen this.

**Comment by kikijiki** [comment]
Actually it looks like boxing for plugins was already introduced a long time ago: https://github.com/tauri-apps/tauri/commit/5e05236b4987346697c7caae0567d3c50714c198#diff-38a38d97761237a269af9bb9565a4a4cb5431f7324e53acf9581c5676eee1039L1209

**Comment by altunenes** [comment]
same issue on my PC too. 
win11 latest

note, this doesnt fix my issue:

```
[target.x86_64-pc-windows-msvc]
rustflags = [
	"-C", "link-arg=/STACK:8000000"
]

# 64 bit Mingw
[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "link-arg=-Wl,--stack,8000000"
]
```

**Comment by HuakunShen** [comment]
> same issue on my PC too. win11 latest
> 
> note, this doesnt fix my issue:
> 
> ```
> [target.x86_64-pc-windows-msvc]
> rustflags = [
> 	"-C", "link-arg=/STACK:8000000"
> ]
> 
> # 64 bit Mingw
> [target.x86_64-pc-windows-gnu]
> rustflags = [
>     "-C", "link-arg=-Wl,--stack,8000000"
> ]
> ```

How many plugins permissions and commands doyou have? Have you tried to increase the stack size beyond 8Mb? and note that the config shouldn’t be added to Cargo.toml, but config.toml

**Comment by altunenes** [comment]
> > same issue on my PC too. win11 latest
> > note, this doesnt fix my issue:
> > ```
> > [target.x86_64-pc-windows-msvc]
> > rustflags = [
> > 	"-C", "link-arg=/STACK:8000000"
> > ]
> > 
> > # 64 bit Mingw
> > [target.x86_64-pc-windows-gnu]
> > rustflags = [
> >     "-C", "link-arg=-Wl,--stack,8000000"
> > ]
> > ```
> 
> How many plugins permissions and commands doyou have? Have you tried to increase the stack size beyond 8Mb? and note that the config shouldn’t be added to Cargo.toml, but config.toml

ah I see, I don't have config.toml. I have had an app in v1 and it worked perfectly I'm trying to migrate into v2 and I saw this error now. 

here is my  ui\src-tauri\capabilities\migrated.json
```
{
  "identifier": "migrated",
  "description": "Permissions that were migrated from v1 and additional required permissions",
  "local": true,
  "windows": [
    "main"
  ],
  "permissions": [
    "core:default",
    "os:default",
    "dialog:default",
    "dialog:allow-open",
    "dialog:allow-save",
    "dialog:allow-ask",
    "dialog:allow-message",
    "fs:allow-remove",
    "fs:allow-read-dir",
    "fs:allow-read-text-file",
    "fs:allow-app-write",
    "process:default",
    "shell:default"
  ]
}
```
```rust
fn main
   ...
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(
            tauri_plugin_log::Builder::new()
                .targets([Target::new(TargetKind::Stdout)])
                .build(),
        )
        
        ...
```


after I manually created config.toml its fixed. Thank you!! <3

 but is it the most appropriate way to solve this? I will be built this app soon on windows for another users. And little bit stressed if this will crash on their pcs :(

**Comment by HuakunShen** [comment]
No idea. I belive it's fine as long as there is no memory leak. But if there is memory leak it would overflow anyway no matter if stack size is increased.
It nows has the same stack size as mac and linux so I assume they should now behave similarly.

**Comment by chippers** [comment]
anybody needing an immediate solution without changing stack size parameters can use

```rust
let context = std::thread::spawn(|| tauri::generate_context!())
  .join()
  .expect("context thread");

tauri::Builder::default()
  // ... snip ...
  .run(context)
  // ... snip ...
```

This is because the default thread stack size is set to 2MiB on all platforms, or higher if the platform sets it higher themselves. The main thread does not default to this.

If you need even MORE stack space, you can use `std::thread::Builder::new().stack_size(bytes)`.

The context creates a lot of things at runtime from items consumed during build time. So there are lots of heap structures created, many of which have their values on the stack before they are passed in. So they all get created at once. With the new ACL system moving to plugins (and therefore the build system and the context), there are many more values - blowing pass the 1MiB size with enough plugins in your dependencies.

I'm looking at ways to get around this.

**Comment by chippers** [comment]
instead of the workaround being adding docs on how to fix this, we could also just use an `8MiB` thread under the hood for the generated context code. would be a workaround for until we simplify the ACL generated code.

literally just wrap the current codegen in
```rust
{
  let thread = ::std::thread::Builder::new()
    .stack_size(8 * 1024 * 1024)
    .spawn(|| /* ... the current codegen output ... */)
    .expect("unable to create thread with 8MiB stack");

  match thread.join() {
    Ok(context) => context,
    Err(e) => panic!(
      "{}",
      e.downcast_ref::<&str>()
        .copied()
        .or_else(|| e.downcast_ref::<String>().map(|x| x.as_str()))
        .unwrap_or("the generated `Context` panicked during creation")
    ),
  }
}
```

(real code would probably grab the last `.expect` from the result and panic with that message, since that is the panic message the thread panicked with)

thoughts? @lucasfernog

**Comment by altunenes** [comment]
> anybody needing an immediate solution without changing stack size parameters can use
> 
> ```rust
> let context = std::thread::spawn(|| tauri::generate_context!())
>   .join()
>   .expect("context thread");
> 
> tauri::Builder::default()
>   // ... snip ...
>   .run(context)
>   // ... snip ...
> ```
> 
> This is because the default thread stack size is set to 2MiB on all platforms, or higher if the platform sets it higher themselves. The main thread does not default to this.
> 
> If you need even MORE stack space, you can use `std::thread::Builder::new().stack_size(bytes)`.
> 
> The context creates a lot of things at runtime from items consumed during build time. So there are lots of heap structures created, many of which have their values on the stack before they are passed in. So they all get created at once. With the new ACL system moving to plugins (and therefore the build system and the context), there are many more values - blowing pass the 1MiB size with enough plugins in your dependencies.
> 
> I'm looking at ways to get around this.

May I ask you if should I have to remove this after I update the latest version of Tauri or keep using it that way still safe? What do you recommend?

**Comment by thewh1teagle** [comment]
I just encountered the same issue on Windows msvc. 

Setting the following env before build fixed it

```console
$env:RUSTFLAGS = "-C link-arg=/STACK:8000000"
```
